### ISSUE TITLE
Using Support.

### ISSUE THREAD

**Issue by cjoulain** [zinc-collective/support#27]
Some questions!

It looks like a license is required to use Support. Do you offer a free trial? How does an interested party know that this product is ideal for their use case? (On the website, sending an email to Zinc is mentioned. I'm guessing this is so you can chat further to discuss whether the product is a good fit for them.)

FAQ section is good and I like how you list out the perks for each paid tier. What made you decide on one inbox for hobbyist edition and four inboxes for indie edition? I'm guessing it's about scale and number of clients but wondered more about that. For the franchise edition, does that mean you create your own inboxes and maintain that? Is a script provided for that?

Are there any testimonials? Or users weighing in on pain points?

**Comment by zspencer** [comment]
These are great questions! I'm going to give @maximegalon5 or the other @zinc-collective/supported-maintainers a chance to lay out thoughts and then try and "yes, and" them.

**Comment by maximegalon5** [comment]
I think we should bundle this as an add-on for We Got Your Back <- which already has pricing etc .. This way we get user feedback and we can survey users for pricing information. 

Alternatively, we add this as a paid add-on or even as a stand-alone a la carte option moving forward <- V 1.0 or 2.0?

Ideally, we should offer 1 month free trial -> monthly subscription / Annual discounted for users.

1 Month free trial -> annual(?) subscription for teams?

**Comment by zspencer** [comment]
Re: Pricing - I agree. I think technically we sell _three_ things.

1. "Buy an Enterprise License" -> Fixed fee, grants you rights to a particular set of versions for Support (i.e. all releases in 2020 and 2021) within your org.  
2. "Subscribe to WGYBT" -> Monthly/Annual subscription with a metered pricing model, focused on the niche of micro-entrepreneurs, Indiedevs, Zebras, Small Coops, etc.
3. "Buy a Franchise License" -> Fixed fee, grants you rights to _resell_ a WGYBT instance targeted towards a particular market niche, like performing artists or small farmers); also includes a %age of gross-revenues.

Re: Decision making on features: I just made them up :). We gotta start somewhere, and am happy to hear suggestions. For instance, I think I'd prefer _metered_ pricing, where we charge you per-non-spam message received or _per-meeting booked_.

Re: Testimonials - Nope, we need to do some more customer development to get those.

Re: Pain points - Need someone to do market-research (ideally by finding people talking about their pain points with our competitors, which would need  us to define our competitors... @maximegalon5 / @cjoulain - Could one of you make an issue to define the market we're focusing on and the competitors in it?)

**Comment by cjoulain** [comment]
Thanks for fielding these questions, Vivek and Zee.

Is it possible for me to get access to a free trial inbox to become more familiar with the product?

I'm more familiar with Cypress but happy to learn more about Cucumber, as I see that's a dependency to this repo.

**Comment by zspencer** [comment]
Re: Free-Trial - For sure! You can either make an issue and when one of the @zinc-collective/supported team members do a "sweep" of new issues we'll add you, or you can submit a patch to the [ClientBuilder](https://github.com/zinc-collective/support/blob/9666744e75bd1e39259e6ec0abe55a9549a5e842/hosted/app/models/client_builder.rb#L1)  which will create the inbox for you on our next deploy.

At present, because Support/WGYBT is an early-stage product there's a lot of hand-holding in onboarding new clients, which we _could_ automate, but it wouldn't really help us drive forward the core value proposition.

Re: Cucumber - Cucumber is a tool for describing features in plain-language; and we mostly use it as a way to [describe what we want the product to do through human-legible examples](https://cucumber.io/docs/bdd/examples/). It can use Cypress or Selenium-Webdriver in it's [step definitions](https://cucumber.io/docs/cucumber/step-definitions/) which act as the "Driver" to exercise the service via it's UI or API. At present, @maximegalon5 and I are exploring how to use [behavior-driven development](https://cucumber.io/docs/bdd/history/) as a way to help contributors know how we intend for the system to work; while generating somewhat useful documentation.

**Comment by zspencer** [comment]
@cjoulain - Are there next steps you'd like us to take on this issue? Further questions? Or are you comfortable closing it in favor of issues for specific user stories or scenarios you'd like us to execute on?

**Comment by zspencer** [comment]
Hey @cjoulain, it's been a few weeks since you've last responded on this issue, so I'm going to close it for now. Feel free to  re-open it or create a new issue if you have further requests for clarification or actions you'd like me to take!

**Comment by cjoulain** [comment]
Yes, thank you! I think #27 is resolved.
